name: Oblique Thoughts
markdown: redcarpet
highlighter: pygments
baseurl: /obliquethoughts

paginate_path: "/page:num"
paginate: 4
excerpt_separator: ""
permalink: /:title/
excerpt_separator: <!--excerpt-->
