name: Oblique Thoughts
markdown: redcarpet
highlighter: pygments
baseurl: /obliquethoughts

paginate_path: "/page:num"
paginate: 3
excerpt_separator: ""
permalink: /:year/:month/:title/
excerpt_separator: <!--excerpt-->
